---
title: "Introducing 'ruml'"
author: "Andreas Blätte (andreas.blaette@uni-due.de)"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introducing 'ruml'}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

## Getting started

```{r load_packages}
library(ruml)
library(plantuml) # install from: https://github.com/rkrug/plantuml
library(magrittr)
```

```{r package_to_analyse}
library(polmineR)
```


## Scenario 1: Create PlantUML Diagram for S4 classes in a package

### Plain plantuml-output

```{r plain_output, results = FALSE}
plantuml_code <- make_plantuml_code("count", pkg = polmineR)
plantuml_obj <- plantuml(plantuml_code)
plot(plantuml_obj, vector = TRUE)
```


### SVG output

[not evaluated]

```{r svg_output, eval = FALSE}
plantuml_svg_file <- tempfile(fileext = ".svg")
svg(filename = plantuml_svg_file)
plot(plantuml_obj, vector = TRUE)
dev.off()
browseURL(url = plantuml_svg_file)
```


### Zoomable output 

```{r zoomable_svg, fig.width = 12}
svglite::xmlSVG(plot(plantuml_obj, vector = TRUE)) %>%
  svgPanZoom::svgPanZoom(width = "100%", height = "100%")
```


## Scenario 2: Create UML for XML (Schema)

### Generate PlantUML code from XML document

```{r plantuml_from_xml, results = FALSE}
xml_file <- system.file(package = "ruml", "extdata", "xml", "shiporder.xml")
make_plantuml_code(xml_file) %>%
  plantuml() %>%
  plot(vector = TRUE)
```


### Generate PlantUML code from XML Schema Definition (XSD)

```{r plantuml_from_xsd, results = FALSE}
xsd_file <- system.file(package = "ruml", "extdata", "xml", "shiporder.xsd")
make_plantuml_code(xsd_file) %>%
  plantuml() %>%
  plot(vector = TRUE)
```


```{r plantuml_from_xsd2, results = FALSE}
xsd_file <- system.file(package = "ruml", "extdata", "xml", "plenaryprotocol.xsd")
make_plantuml_code(xsd_file) %>%
  plantuml() %>%
  plot(vector = TRUE)
```
